# -*- coding: utf-8 -*-
"""5.2-LSTM from scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TcTjQlRRncrO0-yugx6yxxQ34fS178zG

#Recurrent Neural Networks from scratch
In this lab you will implement a basic cell from a Recurrent Neural Network (RNN). The RNN will try to reconstruct a sinusoidal wave.
"""

# Commented out IPython magic to ensure Python compatibility.
import torch
import math
import matplotlib.pyplot as plt

# %matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

torch.manual_seed(8989)

"""##LSTM basic cell

We will implement an LSTM cell in pytorch. Remember the main equations of LSTMs:

$\begin{aligned}
  &x^\prime = \left(\begin{array}{c} h^{<t-1>}\\ x^{<t>} \end{array}\right)\\
  &i = \sigma(\mathbf{W}_{hi}x^\prime + b_{hi})\\
  &f = \sigma(\mathbf{W}_{hf}x^\prime + b_{hf})\\
  &o = \sigma(\mathbf{W}_{ho}x^\prime + b_{ho})\\
  &g = \tanh(\mathbf{W}_{hg}x^\prime + b_{hg})\\
  &c^{<t>} = f \odot c^{<t-1>}+i\odot g\\
  &h^{<t>} = o \odot \tanh(c^{<t>})
\end{aligned}$

Where:
- $x^{<t>}$: input vector at time $t$
- $h^{<t>}$: new state
- $c^{<t>}$: new cell
- $h^{<t-1>}$: previous state
- $c^{<t-1>}$: previous cell

Remember that to implement a layer, you have to create a new class that inherits from `nn.Module`. There are two functions you have to think about:

`__init__` function:


*   Look carefully at the arguments given in its signature.
*   Create tensors for the weights of the layer with the appropriate shape. The shape of our weights is determined by the arguments `input_size`, `hidden_size`.
*   Create the bias tensors with the appropriate shapes.
*   **Remember to wrap the tensors in `torch.nn.Parameter` so they become differentiable parameters**

`forward` function:


*   Given a new input $x^{<t>}$, the previous hidden vector $h^{<t-1>}$ and the previous cell vector $c^{<t-1>}$, calculate $h^{<t>}$ and $c^{<t>}$ (return the output as a tuple)

**EXERCISE:** Implement the layer `LSTMCell` following the instructions above.
"""

class LSTMCell(torch.nn.Module):
    def __init__(self, input_size, hidden_size):
        super(LSTMCell, self).__init__()
        self.hidden_size = hidden_size

        self.w_hi = None
        self.b_hi = None
        self.w_hf = None
        self.b_hf = None
        self.w_hg = None
        self.b_hg = None
        self.w_ho = None
        self.b_ho = None

        # Note, both h and c have the same dimension (hidden_size)

        ### WRITE YOUR CODE HERE ### (~8 lines)

        ########################

        # init parameters
        self.init_parameters()

    def init_parameters(self):
        stdv = 1.0 / math.sqrt(self.hidden_size)
        for weigth in self.parameters():
            with torch.no_grad():
                weigth.uniform_(-stdv, stdv)

    def forward(self, x, h, c):
        '''Perform a one step forward pass.

        Input:
        - x: input tensor at time t (input_size)
        - h: hidden state at time t-1  (hidden_size). Set all zeros for first hidden state.
        - c: cell state at time t-1  (hidden_size). Set all zeros for first cell state.

        Output: a tuple with two values
        - h: next hidden state (hidden_size)
        - c: next cell state (hidden_size)
        '''
        next_h = None
        next_c = None
        ### WRITE YOUR CODE HERE ###
        # You will need the following method:
        # - torch.sigmoid https://pytorch.org/docs/stable/generated/torch.sigmoid.html
        # - torch.tanh https://pytorch.org/docs/stable/generated/torch.tanh.html
        #
        # (~7 line of code)

        ########################
        return next_h, next_c

"""## A class on top the LSTM to predict the new wave value

As the output of the LSTM is $h^{<t>}$, we add a feed forward layer on top of it to predict the next wave value.
"""

class WaveClasif(torch.nn.Module):
    '''A MLP on top of LSTM to predict the nexw wave value'''
    def __init__(self, input_size, hidden_size, output_size):
        super(WaveClasif, self).__init__()
        self.rnn = LSTMCell(input_size, hidden_size)
        self.fcc = torch.nn.Linear(hidden_size, output_size)

    def forward(self, x, h, c):
        next_h, next_c = self.rnn(x, h, c)
        yhat = self.fcc(next_h)
        return yhat, next_h, next_c

"""## Data preparation

We will create the training data. Each example is composed by a pair $(x^{(i)}, y^{(i)})$ where:

- $x^{(i)}$ is a vector corresponding to the wave values $(i,\ldots,i+\mathrm{seq\_len})$
- $y^{(i)}$ is a vector corresponding to the wave values $(i+1,\ldots,i+\mathrm{seq\_len}+1)$


"""

sin_wave = [math.sin(x) for x in torch.arange(200)] + [math.sin(200)] # last element needed in last Y sequence
seq_len = 50
num_records = len(sin_wave)

plt.plot(sin_wave[:200])
plt.show()

##### prepare the training data

X = []
Y = []
for i in range(num_records - seq_len):
    X.append(torch.tensor(sin_wave[i:i+seq_len]))
    Y.append(torch.tensor(sin_wave[i + 1:i+seq_len + 1]))
X = torch.stack(X)
Y = torch.stack(Y)

"""## Train `WaveClasif`(and the LSTM)

Now we will train the WaveClasif` module with the training data.

The training procedure will be the following:

- for each training instance $(x^{(i)}, y^{(i)})$ do:
 - init loss to zero
 - set $h$ and $c$ to zero
 - for j in $1\ldots$ `seq_len`
   - create a one-hot vector $x$ with all zeros except the $j$th component, which is $x^{(i)}_j$
   - call `WaveClasif` with $x$, $h$ and $c$
   - increase loss using the `criterion`function, comparing the output of `WaveClasif`with $y^{(i)}_j$

**EXERCISE**: complete the code within the training loop. **You should obtain a training loss of circa 0.38**
"""

learning_rate = 0.001
nepoch = 50
T = seq_len                   # length of sequence
hidden_size = 100
output_size = 1
rnn = WaveClasif(seq_len, hidden_size, output_size)
criterion = torch.nn.MSELoss() # criterion is mean square loss (sqrt(y_hat^2 - y))
optimizer = torch.optim.SGD(rnn.parameters(), lr=learning_rate) # Stochastic gradient descend

for epoch in range(nepoch):
    losses = []
    for x,y in zip(X, Y):
        ### WRITE YOUR CODE HERE ### (~8 lines of code)

        ########################

        losses.append(loss.item())
        optimizer.zero_grad() # init gradients
        loss.backward()       # compute gradients
        optimizer.step()      # update step
    print(loss.item())
print(f'Train loss {sum(losses)/len(losses)}')

"""## Test the model

We will create a slightly shifted sinusoidal wave and complete it with the results of the trained RNN.

The testing procedure is almost the same to the training procedure, except:

- we iterate through the test dataset
- we only calculate the loss for the last time step
- we do not backpropagate the losses

In summary, write the same code you wrote for training, but **discard all management of the `loss` variable**.

**EXERCISE**: complete the code within the test loop. **You should obtain a test loss of circa $7.45e^{-5}$**
"""

sin_wave_test = [math.sin(math.pi * 0.5 + x) for x in torch.arange(200)] + [math.sin(math.pi * 0.5 + 200)]
X_test = []
Y_test = []
for i in range(num_records - seq_len):
    X_test.append(torch.tensor(sin_wave_test[i:i+seq_len]))
    Y_test.append(torch.tensor(sin_wave_test[i+seq_len]))
X_test = torch.stack(X_test)
Y_test = torch.stack(Y_test)

plt.plot(sin_wave_test[:seq_len])

generated_wave = [0] * seq_len
test_losses = []
with torch.no_grad():
    for x,y in zip(X_test, Y_test):
        ### WRITE YOUR CODE HERE ### (~6 lines of code)

        ########################
        # last yhat predicts y
        generated_wave.append(yhat[0])
        # loss is calculated only for the last time step
        loss = criterion(yhat[0], y)
        test_losses.append(loss.item())
print(f'Test loss: {sum(test_losses)/len(test_losses)}')
plt.plot(generated_wave, '--')
plt.show()

"""## Test the model autorregresively

In the last testing we provided the model the gold input at timestep $t-1$. In this case, we will provide the model its own output in $t-1$ as an input at step $t$, that is, $x^{(t)} = \hat{y}^{(t-1)}$.

The testing procedure is the same as before, except that we feed $\hat{y}^{(t-1)}$ as input in step $t$:

- We only use $x^{<0>}$ as the initial input. All subsequent inputs are provided by the model itself.
- $y^{(i)}$ (the gold value of the next step) **is not used**.
- As before, we discard all management of the `loss` variable.

**EXERCISE**: complete the code within the test loop. **You should obtain a test loss of circa $0.82$**
"""

sin_wave_test = [math.sin(math.pi * 0.5 + x) for x in torch.arange(200)] + [math.sin(math.pi * 0.5 + 200)]
X_test = []
Y_test = []
for i in range(num_records - seq_len):
    X_test.append(torch.tensor(sin_wave_test[i]).unsqueeze(-1)) # tensor of size [1]
    Y_test.append(torch.tensor(sin_wave_test[i+seq_len])) # scalar (tensor of size [])
X_test = torch.stack(X_test)
Y_test = torch.stack(Y_test)

plt.plot(sin_wave_test[:seq_len])

generated_wave = [0] * seq_len
test_losses = []
with torch.no_grad():
    h = torch.zeros(hidden_size)
    for x,_ in zip(X_test, Y_test):
        ### WRITE YOUR CODE HERE (~7 lines of code) ###

        ########################
        # last yhat predicts y
        generated_wave.append(yhat[0])
        # loss is calculated only for the last time step
        loss = criterion(yhat[0], y)
        test_losses.append(loss.item())
print(f'Test loss: {sum(test_losses)/len(test_losses)}')
plt.plot(generated_wave, '--')
plt.show()
