# -*- coding: utf-8 -*-
"""5.1-RNN from scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OBNWcKkYbbQeCC3N8zBKN9JyWuREAvwV

#Recurrent Neural Networks from scratch
In this lab you will implement a basic cell from a Recurrent Neural Network (RNN). The RNN will try to reconstruct a sinusoidal wave.
"""

# Commented out IPython magic to ensure Python compatibility.
import torch
import math
import matplotlib.pyplot as plt

# %matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

torch.manual_seed(8989)

"""##RNN basic cell

We will implement a basic RNN cell in pytorch. Remember the main equations for a basic RNN:

$
\begin{eqnarray*}
h^{<t>} &=& \mathrm{relU}(\mathbf{W}_{h}\left(\begin{array}{c} h^{<t-1>} \\x^{<t>} \end{array}\right) + b_{h})\\
y^{<t>} &=& \mathbf{W}_{y}h^{<t>} + b_{y}
\end{eqnarray*}$

Where:
- $x^{<t>}$: input vector at time $t$
- $h^{<t>}$: new state
- $h^{<t-1>}$: previous state
- $\mathbf{W}_h = \left( \mathbf{W}_{hh}; \mathbf{W}_{hx}\right), \mathbf{W}_y, b_h, b_y$ are the parameters

Remember that to implement a layer, you have to create a new class that inherits from `nn.Module`. There are two functions you have to think about:

`__init__` function:


*   Look carefully at the arguments given in its signature.
*   Create tensors for the weights of the layer with the appropriate shape. The shape of our weights is determined by the arguments `input_size`, `hidden_size` and `output_size`.
*   Create the bias tensors with the appropriate shapes.
*   **Remember to wrap the tensors in `torch.nn.Parameter` so they become differentiable parameters**

`forward` function:


*   Given a new input $x^{<t>}$ and the previous hidden vector $h^{<t-1>}$ calculate $y^{<t>}$ and $h^{<t>}$ (return the output as a tuple)

**EXERCISE:** Implement the layer `RNNCell` following the instructions above.
"""

class RNNCell(torch.nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(RNNCell, self).__init__()
        self.hidden_size = hidden_size

        self.w_h = torch.nn.Parameter(torch.Tensor(hidden_size, input_size + hidden_size))
        self.b_h = torch.nn.Parameter(torch.Tensor(hidden_size))
        self.w_y = torch.nn.Parameter(torch.Tensor(output_size, hidden_size))
        self.b_y = torch.nn.Parameter(torch.Tensor(output_size))

        ### WRITE YOUR CODE HERE (~ 4 lines) ###

        ########################

        # init parameters
        self.init_parameters()

    def init_parameters(self):
        stdv = 1.0 / math.sqrt(self.hidden_size)
        for weigth in self.parameters():
            with torch.no_grad():
                weigth.uniform_(-stdv, stdv)

    def forward(self, x, h):
        '''Perform a one step forward pass.

        Input:
        - x: input tensor at time t (input_size)
        - h: hidden state at time t-1  (hidden_size). Set all zeros for first hidden state.

        Output: a tuple with two values
        - yhat: y output       (output_size)
        - h: next hidden state (hidden_size)
        '''

        ### WRITE YOUR CODE HERE ### (~4 lines)

        concat = torch.cat((h, x), dim=1)
        next_h = torch.relu(torch.matmul(concat, self.w_h.t()) + self.b_h)
        yhat = torch.matmul(next_h, self.w_y.t()) + self.b_y

        ########################
        return yhat, next_h

"""## Data preparation

We will create the training data. Each example is composed by a pair $(x^{(i)}, y^{(i)})$ where:

- $x^{(i)}$ is a tensor of $\mathrm{seq\_len}$ elements vector corresponding to the wave values $(i,\ldots,i+\mathrm{seq\_len})$
- $y^{(i)}$ is a tensor of $\mathrm{seq\_len}$ elements corresponding to the wave values $(i+1,\ldots,i+\mathrm{seq\_len}+1)$


"""

# sin_wave = [2*math.sin(x) * math.cos(x) for x in [x/seq_len for x in torch.arange(200)]]
sin_wave = [math.sin(x) for x in torch.arange(200)] + [math.sin(200)] # last element needed in last Y sequence
seq_len = 50
num_records = len(sin_wave)

plt.plot(sin_wave[:200])
plt.show()

##### prepare the training data

X = []
Y = []
for i in range(num_records - seq_len):
    X.append(torch.tensor(sin_wave[i:i+seq_len]))
    Y.append(torch.tensor(sin_wave[i + 1:i+seq_len + 1]))
X = torch.stack(X)
Y = torch.stack(Y)

"""## Train the RNN

Now we will train the RNN with the training data.

The training procedure will be the following:

- for each training instance $(x^{(i)}, y^{(i)})$ do:
 - init loss to zero
 - set $h$ to zero
 - for j in $1\ldots$ `seq_len`
   - create a one-hot vector $x$ with $\mathrm{seq\_len}$ elements of all zeros, except the $j$th component, which is $x^{(i)}_j$
   - call RNN with $x$ and $h$.
   - increase loss using the `criterion`function, comparing the output of RNN with $y^{(i)}_j$

**EXERCISE**: complete the code within the training loop. **You should obtain a training loss of circa 1.76**
"""

learning_rate = 0.001
nepoch = 40
T = seq_len                   # length of sequence
hidden_size = 100
output_size = 1
rnn = RNNCell(seq_len, hidden_size, output_size)
criterion = torch.nn.MSELoss() # criterion is mean square loss (sqrt(y_hat^2 - y))
optimizer = torch.optim.SGD(rnn.parameters(), lr=learning_rate) # Stochastic gradient descend
losses = []
for epoch in range(nepoch):
    for x,y in zip(X, Y):
        ### WRITE YOUR CODE HERE (~7 lines of code) ######
        loss=0.0
        h=torch.zeros(1,hidden_size)
        for j in range(T):
          x_onehot=torch.zeros(1,T)
          x_onehot[0,j]=x[j]
          y_hat, h=rnn(x_onehot, h)
          loss+=criterion(y_hat,y[j].view(1,1))

        ########################
        losses.append(loss.item())
        optimizer.zero_grad() # init gradients
        loss.backward()       # compute gradients
        optimizer.step()      # update step
    print(loss.item())
print(f'Train loss {sum(losses)/len(losses)}')

"""## Test the model

For testing the model, we will create a slightly shifted sinusoidal wave and complete it with the results of the trained RNN. The testing procedure is almost the same to the training procedure, except:

- Data is slightly different: $x^{(i)}$ is a tensor of $\mathrm{seq\_len}$ values in the sine wave, and $y^{(i)}$ is a scalar with the next value (corresponding to timestep $\mathrm{seq\_len} + 1$) of the sine wave.
- we only calculate the loss for the last time step
- we do not backpropagate the losses

In summary, write the same code you wrote for training, but **discard all management of the `loss` variable**.


**EXERCISE**: complete the code within the test loop. **You should obtain a test loss of circa $7.6e^{-5}$**
"""

sin_wave_test = [math.sin(math.pi * 0.5 + x) for x in torch.arange(200)] + [math.sin(math.pi * 0.5 + 200)]
X_test = []
Y_test = []
for i in range(num_records - seq_len):
    X_test.append(torch.tensor(sin_wave_test[i:i+seq_len]))
    Y_test.append(torch.tensor(sin_wave_test[i+seq_len]))
X_test = torch.stack(X_test)
Y_test = torch.stack(Y_test)

plt.plot(sin_wave_test[:seq_len])

generated_wave = [0] * seq_len
test_losses = []
with torch.no_grad():
    for x,y in zip(X_test, Y_test):
        ### WRITE YOUR CODE HERE (~5 lines of code) ###

        h=torch.zeros(1,hidden_size)
        for j in range(T):
          x_onehot=torch.zeros(1,T)
          x_onehot[0,j]=x[j]
          yhat, h=rnn(x_onehot, h)


        ########################
        # last yhat predicts y
        generated_wave.append(yhat[0].item()) # Convert the tensor to a Python float
        # loss is calculated only for the last time step
        loss = criterion(yhat[0], y)
        test_losses.append(loss.item())
print(f'Test loss: {sum(test_losses)/len(test_losses)}')
plt.plot(generated_wave, '--')
plt.show()

"""## Test the model autorregresively

In the last testing we provided the model the gold input at timestep $t-1$. In this case, we will provide the model its own output in $t-1$ as an input at step $t$, that is, $x^{(t)} = \hat{y}^{(t-1)}$.

The testing procedure is the same as before, except that we feed $\hat{y}^{(t-1)}$ as input in step $t$:

- We only use $x^{<0>}$ as the initial input. All subsequent inputs are provided by the model itself.
- $y^{(i)}$ (the gold value of the next step) **is not used**.
- As before, we discard all management of the `loss` variable.

**EXERCISE**: complete the code within the test loop. **You should obtain a test loss of circa $1.08$**
"""

sin_wave_test = [math.sin(math.pi * 0.5 + x) for x in torch.arange(200)] + [math.sin(math.pi * 0.5 + 200)]
X_test = []
Y_test = []
for i in range(num_records - seq_len):
    X_test.append(torch.tensor(sin_wave_test[i]).unsqueeze(-1)) # tensor of size [1]
    Y_test.append(torch.tensor(sin_wave_test[i+seq_len])) # scalar (tensor of size [])
X_test = torch.stack(X_test)
Y_test = torch.stack(Y_test)

plt.plot(sin_wave_test[:seq_len])

generated_wave = [0] * seq_len
test_losses = []
with torch.no_grad():
    for x,y in zip(X_test, Y_test):
        ### WRITE YOUR CODE HERE (~5 lines of code) ###
        h = torch.zeros(1, hidden_size)
        yhat = None
        for j in range(T):
            x_in = torch.zeros(1, T)
            x_in[0, j] = x[0] if j == 0 else yhat.item()
            yhat, h = rnn(x_in, h)


        ########################
        # last yhat predicts y
        generated_wave.append(yhat[0].item())
        # loss is calculated only for the last time step
        loss = criterion(yhat[0], y)
        test_losses.append(loss.item())
print(f'Test loss: {sum(test_losses)/len(test_losses)}')
plt.plot(generated_wave, '--')
plt.show()
